server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kida10-tech/vehicles-microservices.git
          searchPaths: config-data
          default-label: "main"
  application:
    name: config-service
security:
  user:
    name: root
    password: secret
